#ifndef PYTHONGRABBRUSH_H__
#define PYTHONGRABBRUSH_H__

enum
{
    PythonGrabBrush_Start = 20000,
    MDATA_PYTHONGRABBRUSH_DIRMODE,
    MDATA_PYTHONGRABBRUSH_DIRMODE_MOUSEDIR,
    MDATA_PYTHONGRABBRUSH_DIRMODE_NORMAL,
};

#endif	// PYTHONGRABBRUSH_H__
