CONTAINER pythontwistbrush
{
    NAME pythontwistbrush;
    INCLUDE toolsculptbrushbase;
 
    HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE;
    HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;
    HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;
}
