CONTAINER Opyspherifymodifier
{
	NAME Opyspherifymodifier;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PYSPHERIFYMODIFIER_RADIUS	   { UNIT METER; MIN 0.0; }
		REAL PYSPHERIFYMODIFIER_STRENGTH	 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}
