CONTAINER pypreference
{
	NAME pypreference;

	GROUP PYPREFERENCE_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		BOOL PYPREFERENCE_CHECK			{ ANIM OFF; }
		LONG PYPREFERENCE_NUMBER		{ MIN 1; MAX 1000; }
	}
}
