#ifndef PYPREFERENCE_H__
#define PYPREFERENCE_H__

enum
{
	PYPREFERENCE_MAIN_GROUP					= 999,
	PYPREFERENCE_CHECK							= 1000,
	PYPREFERENCE_NUMBER							= 1001,

	PYPREFERENCE_DUMMY
};

#endif // PYPREFERENCE_H__
