#ifndef _Opysculptmodifierdeformer_H_
#define _Opysculptmodifierdeformer_H_

enum
{
    PYSCULPTMODIFIERDEFORMER_RADIUS			= 1000,
    PYSCULPTMODIFIERDEFORMER_PRESSURE		= 1001,
    PYSCULPTMODIFIERDEFORMER_STAMP_TEXTURE = 1002,
    PYSCULPTMODIFIERDEFORMER_STAMP_ACTIVE = 1003,
    PYSCULPTMODIFIERDEFORMER_NUMSTAMPS = 1005,
    PYSCULPTMODIFIERDEFORMER_STAMP_USEFALLOFF = 1007,
    PYSCULPTMODIFIERDEFORMER_SEED = 1008,
    PYSCULPTMODIFIERDEFORMER_STAMP_ROTATION = 1009,
};

#endif