CONTAINER opydynamicparametersobject
{
	NAME opydynamicparametersobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL OPYDYNAMICPARAMETERSOBJECT_TRANSLATED_PHONG_ANGLE { UNIT DEGREE; }
		LONG OPYDYNAMICPARAMETERSOBJECT_PARAMETERSNUMBER { MIN 1; MAX 100; }
	}
}
