CONTAINER Opyspheredeformer
{
	NAME Opyspheredeformer;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PY_SPHERE_DEFORMER_RADIUS { UNIT METER; MIN 0.0; }
		REAL PY_SPHERE_DEFORMER_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}
